services:
  postgres:
    image: postgres:15-alpine
    container_name: alimento_db
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alimento_db
